grails-app/domain/com/twc/TempConversion.groovy
package com.twc


/**
 * The Class TempConversion.
 */
class TempConversion {
	
	/** The from temp. */
	Float fromTemp
	
	/** The to temp. */
	Float toTemp
	
	/** The from unit. */
	String fromUnit
	
	/** The to unit. */
	String toUnit
	
	//static transients = ['fromTemp', 'toTemp', 'fromUnit', 'toUnit']
    
    /** The constraints. */
    static constraints = {
    }
}

grails-app/controllers/com/twc/TempConversionController.groovy
package com.twc



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import org.grails.plugins.wsclient.service.WebService


/**
 * The Class TempConversionController.
 */
@Transactional(readOnly = true)
class TempConversionController {
	
	/** The web service. */
	WebService webService
    
    /** The allowed methods. */
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    /**
     * Index.
     *
     * @return the java.lang. object
     */
    def index() {
      
    }

    

    /**
     * Convert.
     *
     * @return the java.lang. object
     */
    def convert() {
        respond new TempConversion(params)
    }
	
	/**
	 * Call ws.
	 *
	 * @return the java.lang. object
	 */
	def callWs() {
		
		def wsdlURL = "http://www.webservicex.net/ConvertTemperature.asmx?WSDL"
		def proxy = webService.getClient(wsdlURL)

		def result = proxy.ConvertTemp(params.fromTemp, params.fromUnit, params.toUnit)
		
		render(status: 200, text: '&nbsp;&nbsp;&nbsp;&nbsp; Converted Temperature is '+result +' '+params.toUnit)
	}
   
}

grails-app/views/tempConversion/_form.gsp
<%@ page import="com.twc.TempConversion" %>

grails-app/views/tempConversion/convert.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tempConversion.label', default: 'TempConversion')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
		<g:javascript library="jquery"/>
	</head>
	<body>
		<a href="#create-tempConversion" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<%--<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		--%><div id="create-tempConversion" class="content scaffold-create" role="main">
			<h1><g:message code="default.conversion.label" args="[entityName]" default="Temperature Conversion Program"/></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${tempConversionInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${tempConversionInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<div id="convForm">
				<fieldset class="form">
				From Temperature	<g:field name="fromTemp" type="text"/></br></br>
				From Unit	<g:select name="fromUnit" from="${['degreeCelsius', 'degreeFahrenheit', 'degreeRankine', 'degreeReaumur', 'kelvin']}" value=""
          		noSelection="['':'-Choose from unit-']"/></br></br>
				To Unit 	<g:select name="toUnit" from="${['degreeCelsius', 'degreeFahrenheit', 'degreeRankine', 'degreeReaumur', 'kelvin']}" value=""
          		noSelection="['':'-Choose to unit-']"/></br></br>
				</fieldset>
				<fieldset class="buttons">
					<button onclick="callme()">Convert</button>
    
				</fieldset>
			</div>
		</div>
		</br>
		</br>
		<div id="converted"></div>
		</br>
		<script type="text/javascript">
		
		function callme(){
			//var formData = $('#convForm').serialize();
			var fromTemp =  $('#fromTemp').val();
			var fromUnit =  $('#fromUnit').val();
			var toUnit =  $('#toUnit').val();
			jQuery.ajax({type:'POST',
				data:  {
					fromTemp: fromTemp,
					fromUnit: fromUnit,
					toUnit: toUnit
					
				},
				url:'/TWC/tempConversion/callWs',
				success:function(data,textStatus){
					jQuery('#converted').html(data);
					},
				error:function(XMLHttpRequest,textStatus,errorThrown){}
				});
			
			
			
			}
		</script>
	</body>
</html>

grails-app/views/tempConversion/edit.gsp
<%@ page import="com.twc.TempConversion" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tempConversion.label', default: 'TempConversion')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-tempConversion" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="convert"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-tempConversion" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${tempConversionInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${tempConversionInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:tempConversionInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${tempConversionInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/tempConversion/index.gsp
<%@ page import="com.twc.TempConversion" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tempConversion.label', default: 'TempConversion')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-tempConversion" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="convert"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-tempConversion" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${tempConversionInstanceList}" status="i" var="tempConversionInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${tempConversionInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/tempConversion/show.gsp
<%@ page import="com.twc.TempConversion" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tempConversion.label', default: 'TempConversion')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-tempConversion" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="convert"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-tempConversion" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list tempConversion">
			
			</ol>
			<g:form url="[resource:tempConversionInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${tempConversionInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>