grails-app/domain/com/twc/PhoneNumber.groovy
package com.twc


/**
 * The Class PhoneNumber.
 */
class PhoneNumber {
	
	/** The number. */
	String number
	
	/** The is active. */
	boolean isActive
	
	/** The belongs to. */
	static belongsTo = [customer: Customer]
    
    /** The constraints. */
    static constraints = {
    }
}

grails-app/controllers/com/twc/PhoneNumberController.groovy
package com.twc



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional


/**
 * The Class PhoneNumberController.
 */
@Transactional(readOnly = true)
class PhoneNumberController {

    /** The allowed methods. */
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    /**
     * Index.
     *
     * @param max the max
     * @return the java.lang. object
     */
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond PhoneNumber.list(params), model:[phoneNumberInstanceCount: PhoneNumber.count()]
    }

    /**
     * Show.
     *
     * @param phoneNumberInstance the phone number instance
     * @return the java.lang. object
     */
    def show(PhoneNumber phoneNumberInstance) {
        respond phoneNumberInstance
    }

    /**
     * Creates the.
     *
     * @return the java.lang. object
     */
    def create() {
        respond new PhoneNumber(params)
    }

    /**
     * Save.
     *
     * @param phoneNumberInstance the phone number instance
     * @return the java.lang. object
     */
    @Transactional
    def save(PhoneNumber phoneNumberInstance) {
        if (phoneNumberInstance == null) {
            notFound()
            return
        }

        if (phoneNumberInstance.hasErrors()) {
            respond phoneNumberInstance.errors, view:'create'
            return
        }

        phoneNumberInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'phoneNumberInstance.label', default: 'PhoneNumber'), phoneNumberInstance.id])
                redirect phoneNumberInstance
            }
            '*' { respond phoneNumberInstance, [status: CREATED] }
        }
    }

    /**
     * Edits the.
     *
     * @param phoneNumberInstance the phone number instance
     * @return the java.lang. object
     */
    def edit(PhoneNumber phoneNumberInstance) {
        respond phoneNumberInstance
    }

    /**
     * Update.
     *
     * @param phoneNumberInstance the phone number instance
     * @return the java.lang. object
     */
    @Transactional
    def update(PhoneNumber phoneNumberInstance) {
        if (phoneNumberInstance == null) {
            notFound()
            return
        }

        if (phoneNumberInstance.hasErrors()) {
            respond phoneNumberInstance.errors, view:'edit'
            return
        }

        phoneNumberInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'PhoneNumber.label', default: 'PhoneNumber'), phoneNumberInstance.id])
                redirect phoneNumberInstance
            }
            '*'{ respond phoneNumberInstance, [status: OK] }
        }
    }

    /**
     * Delete.
     *
     * @param phoneNumberInstance the phone number instance
     * @return the java.lang. object
     */
    @Transactional
    def delete(PhoneNumber phoneNumberInstance) {

        if (phoneNumberInstance == null) {
            notFound()
            return
        }

        phoneNumberInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'PhoneNumber.label', default: 'PhoneNumber'), phoneNumberInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    /**
     * Not found.
     */
    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'phoneNumberInstance.label', default: 'PhoneNumber'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/phoneNumber/_form.gsp
<%@ page import="com.twc.PhoneNumber" %>



<div class="fieldcontain ${hasErrors(bean: phoneNumberInstance, field: 'customer', 'error')} required">
	<label for="customer">
		<g:message code="phoneNumber.customer.label" default="Customer" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="customer" name="customer.id" from="${com.twc.Customer.list()}" optionKey="id" required="" value="${phoneNumberInstance?.customer?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: phoneNumberInstance, field: 'isActive', 'error')} ">
	<label for="isActive">
		<g:message code="phoneNumber.isActive.label" default="Is Active" />
		
	</label>
	<g:checkBox name="isActive" value="${phoneNumberInstance?.isActive}" />
</div>

<div class="fieldcontain ${hasErrors(bean: phoneNumberInstance, field: 'number', 'error')} ">
	<label for="number">
		<g:message code="phoneNumber.number.label" default="Number" />
		
	</label>
	<g:textField name="number" value="${phoneNumberInstance?.number}"/>
</div>

grails-app/views/phoneNumber/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'phoneNumber.label', default: 'PhoneNumber')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-phoneNumber" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-phoneNumber" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${phoneNumberInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${phoneNumberInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:phoneNumberInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/phoneNumber/edit.gsp
<%@ page import="com.twc.PhoneNumber" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'phoneNumber.label', default: 'PhoneNumber')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-phoneNumber" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-phoneNumber" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${phoneNumberInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${phoneNumberInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:phoneNumberInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${phoneNumberInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/phoneNumber/index.gsp
<%@ page import="com.twc.PhoneNumber" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'phoneNumber.label', default: 'PhoneNumber')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-phoneNumber" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-phoneNumber" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="phoneNumber.customer.label" default="Customer" /></th>
					
						<g:sortableColumn property="isActive" title="${message(code: 'phoneNumber.isActive.label', default: 'Is Active')}" />
					
						<g:sortableColumn property="number" title="${message(code: 'phoneNumber.number.label', default: 'Number')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${phoneNumberInstanceList}" status="i" var="phoneNumberInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${phoneNumberInstance.id}">${fieldValue(bean: phoneNumberInstance, field: "customer")}</g:link></td>
					
						<td><g:formatBoolean boolean="${phoneNumberInstance.isActive}" /></td>
					
						<td>${fieldValue(bean: phoneNumberInstance, field: "number")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${phoneNumberInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/phoneNumber/show.gsp
<%@ page import="com.twc.PhoneNumber" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'phoneNumber.label', default: 'PhoneNumber')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-phoneNumber" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-phoneNumber" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list phoneNumber">
			
				<g:if test="${phoneNumberInstance?.customer}">
				<li class="fieldcontain">
					<span id="customer-label" class="property-label"><g:message code="phoneNumber.customer.label" default="Customer" /></span>
					
						<span class="property-value" aria-labelledby="customer-label"><g:link controller="customer" action="show" id="${phoneNumberInstance?.customer?.id}">${phoneNumberInstance?.customer?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${phoneNumberInstance?.isActive}">
				<li class="fieldcontain">
					<span id="isActive-label" class="property-label"><g:message code="phoneNumber.isActive.label" default="Is Active" /></span>
					
						<span class="property-value" aria-labelledby="isActive-label"><g:formatBoolean boolean="${phoneNumberInstance?.isActive}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${phoneNumberInstance?.number}">
				<li class="fieldcontain">
					<span id="number-label" class="property-label"><g:message code="phoneNumber.number.label" default="Number" /></span>
					
						<span class="property-value" aria-labelledby="number-label"><g:fieldValue bean="${phoneNumberInstance}" field="number"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:phoneNumberInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${phoneNumberInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>