grails-app/domain/com/twc/Customer.groovy
package com.twc


/**
 * The Class Customer.
 */
class Customer {
	
	/** The name. */
	String name
	
	/** The has many. */
	static hasMany = [phoneNumbers: PhoneNumber]
    
    /** The constraints. */
    static constraints = {
    }
}

grails-app/controllers/com/twc/CustomerController.groovy
package com.twc



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import com.twc.PhoneNumberService


/**
 * The Class CustomerController.
 */
@Transactional(readOnly = true)
class CustomerController {
	
	/** The phone number service. */
	def phoneNumberService 
    
    /** The allowed methods. */
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    /**
     * Index.
     *
     * @param max the max
     * @return the java.lang. object
     */
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Customer.list(params), model:[customerInstanceCount: Customer.count()]
    }

    /**
     * Show.
     *
     * @param customerInstance the customer instance
     * @return the java.lang. object
     */
    def show(Customer customerInstance) {
        respond customerInstance
    }

    /**
     * Creates the.
     *
     * @return the java.lang. object
     */
    def create() {
        respond new Customer(params)
    }

    /**
     * Save.
     *
     * @param customerInstance the customer instance
     * @return the java.lang. object
     */
    @Transactional
    def save(Customer customerInstance) {
        if (customerInstance == null) {
            notFound()
            return
        }

        if (customerInstance.hasErrors()) {
            respond customerInstance.errors, view:'create'
            return
        }

        customerInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'customerInstance.label', default: 'Customer'), customerInstance.id])
                redirect customerInstance
            }
            '*' { respond customerInstance, [status: CREATED] }
        }
    }

    /**
     * Edits the.
     *
     * @param customerInstance the customer instance
     * @return the java.lang. object
     */
    def edit(Customer customerInstance) {
        respond customerInstance
    }

    /**
     * Update.
     *
     * @param customerInstance the customer instance
     * @return the java.lang. object
     */
    @Transactional
    def update(Customer customerInstance) {
        if (customerInstance == null) {
            notFound()
            return
        }

        if (customerInstance.hasErrors()) {
            respond customerInstance.errors, view:'edit'
            return
        }

        customerInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Customer.label', default: 'Customer'), customerInstance.id])
                redirect customerInstance
            }
            '*'{ respond customerInstance, [status: OK] }
        }
    }

    /**
     * Delete.
     *
     * @param customerInstance the customer instance
     * @return the java.lang. object
     */
    @Transactional
    def delete(Customer customerInstance) {

        if (customerInstance == null) {
            notFound()
            return
        }

        customerInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Customer.label', default: 'Customer'), customerInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    /**
     * Not found.
     */
    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'customerInstance.label', default: 'Customer'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
	
	/**
	 * Test.
	 *
	 * @return the java.lang. object
	 */
	def test(){
		println(// TODO: Auto-generated Javadoc

/**
 * Run.
 *
 * @return the java.lang. object
 */
phoneNumberService.getAllPhoneNumbers())
	}
}

grails-app/controllers/com/twc/PhoneNumberController.groovy
package com.twc



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional


/**
 * The Class PhoneNumberController.
 */
@Transactional(readOnly = true)
class PhoneNumberController {

    /** The allowed methods. */
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    /**
     * Index.
     *
     * @param max the max
     * @return the java.lang. object
     */
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond PhoneNumber.list(params), model:[phoneNumberInstanceCount: PhoneNumber.count()]
    }

    /**
     * Show.
     *
     * @param phoneNumberInstance the phone number instance
     * @return the java.lang. object
     */
    def show(PhoneNumber phoneNumberInstance) {
        respond phoneNumberInstance
    }

    /**
     * Creates the.
     *
     * @return the java.lang. object
     */
    def create() {
        respond new PhoneNumber(params)
    }

    /**
     * Save.
     *
     * @param phoneNumberInstance the phone number instance
     * @return the java.lang. object
     */
    @Transactional
    def save(PhoneNumber phoneNumberInstance) {
        if (phoneNumberInstance == null) {
            notFound()
            return
        }

        if (phoneNumberInstance.hasErrors()) {
            respond phoneNumberInstance.errors, view:'create'
            return
        }

        phoneNumberInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'phoneNumberInstance.label', default: 'PhoneNumber'), phoneNumberInstance.id])
                redirect phoneNumberInstance
            }
            '*' { respond phoneNumberInstance, [status: CREATED] }
        }
    }

    /**
     * Edits the.
     *
     * @param phoneNumberInstance the phone number instance
     * @return the java.lang. object
     */
    def edit(PhoneNumber phoneNumberInstance) {
        respond phoneNumberInstance
    }

    /**
     * Update.
     *
     * @param phoneNumberInstance the phone number instance
     * @return the java.lang. object
     */
    @Transactional
    def update(PhoneNumber phoneNumberInstance) {
        if (phoneNumberInstance == null) {
            notFound()
            return
        }

        if (phoneNumberInstance.hasErrors()) {
            respond phoneNumberInstance.errors, view:'edit'
            return
        }

        phoneNumberInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'PhoneNumber.label', default: 'PhoneNumber'), phoneNumberInstance.id])
                redirect phoneNumberInstance
            }
            '*'{ respond phoneNumberInstance, [status: OK] }
        }
    }

    /**
     * Delete.
     *
     * @param phoneNumberInstance the phone number instance
     * @return the java.lang. object
     */
    @Transactional
    def delete(PhoneNumber phoneNumberInstance) {

        if (phoneNumberInstance == null) {
            notFound()
            return
        }

        phoneNumberInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'PhoneNumber.label', default: 'PhoneNumber'), phoneNumberInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    /**
     * Not found.
     */
    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'phoneNumberInstance.label', default: 'PhoneNumber'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/customer/_form.gsp
<%@ page import="com.twc.Customer" %>



<div class="fieldcontain ${hasErrors(bean: customerInstance, field: 'name', 'error')} ">
	<label for="name">
		<g:message code="customer.name.label" default="Name" />
		
	</label>
	<g:textField name="name" value="${customerInstance?.name}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: customerInstance, field: 'phoneNumbers', 'error')} ">
	<label for="phoneNumbers">
		<g:message code="customer.phoneNumbers.label" default="Phone Numbers" />
		
	</label>
	<g:select name="phoneNumbers" from="${com.twc.PhoneNumber.list()}" multiple="multiple" optionKey="id" size="5" value="${customerInstance?.phoneNumbers*.id}" class="many-to-many"/>
</div>

grails-app/views/customer/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'customer.label', default: 'Customer')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-customer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-customer" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${customerInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${customerInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:customerInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/customer/edit.gsp
<%@ page import="com.twc.Customer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'customer.label', default: 'Customer')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-customer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-customer" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${customerInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${customerInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:customerInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${customerInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/customer/index.gsp
<%@ page import="com.twc.Customer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'customer.label', default: 'Customer')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-customer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-customer" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'customer.name.label', default: 'Name')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${customerInstanceList}" status="i" var="customerInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${customerInstance.id}">${fieldValue(bean: customerInstance, field: "name")}</g:link></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${customerInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/customer/show.gsp
<%@ page import="com.twc.Customer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'customer.label', default: 'Customer')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-customer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-customer" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list customer">
			
				<g:if test="${customerInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="customer.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${customerInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${customerInstance?.phoneNumbers}">
				<li class="fieldcontain">
					<span id="phoneNumbers-label" class="property-label"><g:message code="customer.phoneNumbers.label" default="Phone Numbers" /></span>
					
						<g:each in="${customerInstance.phoneNumbers}" var="p">
						<span class="property-value" aria-labelledby="phoneNumbers-label"><g:link controller="phoneNumber" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:customerInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${customerInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>