grails-app/domain/com/twc/FileContents.groovy
package com.twc
import javax.management.modelmbean.RequiredModelMBean;

/**
 * The Class FileContents.
 */
class FileContents {

	/** The user id. */
	String userId

	/** The amount of coins. */
	Integer amountOfCoins

	/** The user name. */
	String userName

	/** The constraints. */
	static constraints = {
		userId (blank: false, size: 10..10)
		amountOfCoins (blank: false)
		userName (blank: false)
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "FileContents [userId=" + userId + ", amountOfCoins="
		+ amountOfCoins + ", userName=" + userName + "]";
	}
}

grails-app/controllers/com/twc/FileContentsController.groovy
package com.twc



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional


/**
 * The Class FileContentsController.
 */
@Transactional(readOnly = true)
class FileContentsController {

	/** The allowed methods. */
	static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

	/**
	 * Index.
	 *
	 * @return the java.lang. object
	 */
	def index() {
		render(view: "upload")
	}
	
	/**
	 * Upload.
	 *
	 * @return the java.lang. object
	 */
	@Transactional
	def upload() {

		def count = 0
		params?.file?.inputStream?.toCsvReader()?.eachLine { tokens ->

			try{
				def fileContents = new FileContents()
				fileContents.userId = tokens[0]
				fileContents.amountOfCoins = Integer.parseInt(tokens[1]?.trim())
				fileContents.userName = tokens[2]
				
				if(!fileContents.validate()){
					
					throw new Exception(fileContents.errors.toString())
				}else{
					fileContents.save(flush:true)
				}
				count++
			}
			catch(Exception e){
				count++
				flash.message ="Error on line number "+count +", problem is "+e.getMessage()
				render(view: "upload")
				return;
			}
			flash.message ="File's content saved successfully"
			render(view: "upload")
		}
	}
	
	/**
	 * Show.
	 *
	 * @param fileContentsInstance the file contents instance
	 * @return the java.lang. object
	 */
	def show(FileContents fileContentsInstance) {
		respond fileContentsInstance
	}

	/**
	 * Creates the.
	 *
	 * @return the java.lang. object
	 */
	def create() {
		respond new FileContents(params)
	}

	/**
	 * Save.
	 *
	 * @param fileContentsInstance the file contents instance
	 * @return the java.lang. object
	 */
	@Transactional
	def save(FileContents fileContentsInstance) {
		if (fileContentsInstance == null) {
			notFound()
			return
		}

		if (fileContentsInstance.hasErrors()) {
			respond fileContentsInstance.errors, view:'create'
			return
		}

		fileContentsInstance.save flush:true

		request.withFormat {
			form {
				flash.message = message(code: 'default.created.message', args: [
					message(code: 'fileContentsInstance.label', default: 'FileContents'),
					fileContentsInstance.id
				])
				redirect fileContentsInstance
			}
			'*' { respond fileContentsInstance, [status: CREATED] }
		}
	}

	/**
	 * Edits the.
	 *
	 * @param fileContentsInstance the file contents instance
	 * @return the java.lang. object
	 */
	def edit(FileContents fileContentsInstance) {
		respond fileContentsInstance
	}

	/**
	 * Update.
	 *
	 * @param fileContentsInstance the file contents instance
	 * @return the java.lang. object
	 */
	@Transactional
	def update(FileContents fileContentsInstance) {
		if (fileContentsInstance == null) {
			notFound()
			return
		}

		if (fileContentsInstance.hasErrors()) {
			respond fileContentsInstance.errors, view:'edit'
			return
		}

		fileContentsInstance.save flush:true

		request.withFormat {
			form {
				flash.message = message(code: 'default.updated.message', args: [
					message(code: 'FileContents.label', default: 'FileContents'),
					fileContentsInstance.id
				])
				redirect fileContentsInstance
			}
			'*'{ respond fileContentsInstance, [status: OK] }
		}
	}

	/**
	 * Delete.
	 *
	 * @param fileContentsInstance the file contents instance
	 * @return the java.lang. object
	 */
	@Transactional
	def delete(FileContents fileContentsInstance) {

		if (fileContentsInstance == null) {
			notFound()
			return
		}

		fileContentsInstance.delete flush:true

		request.withFormat {
			form {
				flash.message = message(code: 'default.deleted.message', args: [
					message(code: 'FileContents.label', default: 'FileContents'),
					fileContentsInstance.id
				])
				redirect action:"index", method:"GET"
			}
			'*'{ render status: NO_CONTENT }
		}
	}

	/**
	 * Not found.
	 */
	protected void notFound() {
		request.withFormat {
			form {
				flash.message = message(code: 'default.not.found.message', args: [
					message(code: 'fileContentsInstance.label', default: 'FileContents'),
					params.id
				])
				redirect action: "index", method: "GET"
			}
			'*'{ render status: NOT_FOUND }
		}
	}
}

grails-app/views/fileContents/_form.gsp
<%@ page import="com.twc.FileContents" %>



<div class="fieldcontain ${hasErrors(bean: fileContentsInstance, field: 'userId', 'error')} required">
	<label for="userId">
		<g:message code="fileContents.userId.label" default="User Id" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="userId" required="" value="${fileContentsInstance?.userId}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: fileContentsInstance, field: 'amountOfCoins', 'error')} required">
	<label for="amountOfCoins">
		<g:message code="fileContents.amountOfCoins.label" default="Amount Of Coins" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="amountOfCoins" type="number" value="${fileContentsInstance.amountOfCoins}" required=""/>
</div>

<div class="fieldcontain ${hasErrors(bean: fileContentsInstance, field: 'userName', 'error')} required">
	<label for="userName">
		<g:message code="fileContents.userName.label" default="User Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="userName" required="" value="${fileContentsInstance?.userName}"/>
</div>

grails-app/views/fileContents/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'fileContents.label', default: 'FileContents')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-fileContents" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-fileContents" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${fileContentsInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${fileContentsInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:fileContentsInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/fileContents/edit.gsp
<%@ page import="com.twc.FileContents" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'fileContents.label', default: 'FileContents')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-fileContents" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-fileContents" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${fileContentsInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${fileContentsInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:fileContentsInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${fileContentsInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/fileContents/index.gsp
<%@ page import="com.twc.FileContents" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'fileContents.label', default: 'FileContents')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-fileContents" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-fileContents" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="userId" title="${message(code: 'fileContents.userId.label', default: 'User Id')}" />
					
						<g:sortableColumn property="amountOfCoins" title="${message(code: 'fileContents.amountOfCoins.label', default: 'Amount Of Coins')}" />
					
						<g:sortableColumn property="userName" title="${message(code: 'fileContents.userName.label', default: 'User Name')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${fileContentsInstanceList}" status="i" var="fileContentsInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${fileContentsInstance.id}">${fieldValue(bean: fileContentsInstance, field: "userId")}</g:link></td>
					
						<td>${fieldValue(bean: fileContentsInstance, field: "amountOfCoins")}</td>
					
						<td>${fieldValue(bean: fileContentsInstance, field: "userName")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${fileContentsInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/fileContents/show.gsp
<%@ page import="com.twc.FileContents" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'fileContents.label', default: 'FileContents')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-fileContents" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-fileContents" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list fileContents">
			
				<g:if test="${fileContentsInstance?.userId}">
				<li class="fieldcontain">
					<span id="userId-label" class="property-label"><g:message code="fileContents.userId.label" default="User Id" /></span>
					
						<span class="property-value" aria-labelledby="userId-label"><g:fieldValue bean="${fileContentsInstance}" field="userId"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${fileContentsInstance?.amountOfCoins}">
				<li class="fieldcontain">
					<span id="amountOfCoins-label" class="property-label"><g:message code="fileContents.amountOfCoins.label" default="Amount Of Coins" /></span>
					
						<span class="property-value" aria-labelledby="amountOfCoins-label"><g:fieldValue bean="${fileContentsInstance}" field="amountOfCoins"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${fileContentsInstance?.userName}">
				<li class="fieldcontain">
					<span id="userName-label" class="property-label"><g:message code="fileContents.userName.label" default="User Name" /></span>
					
						<span class="property-value" aria-labelledby="userName-label"><g:fieldValue bean="${fileContentsInstance}" field="userName"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:fileContentsInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${fileContentsInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/fileContents/upload.gsp
<%@ page import="com.twc.FileContents" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'fileContents.label', default: 'FileContents')}" />
		<title><g:message code="default.upload.label" args="[entityName]" /></title>
	</head>
	<body>
	<h1><g:message code="default.upload.label" args="[entityName]" default="Please upload the file containg data"/></h1>
		<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
		</g:if>
		</br>
		<g:uploadForm action="upload">
		    <input type="file" name="file">
		    <g:submitButton name="upload" value="Upload"/>
		</g:uploadForm>
	</body>
</html>